### ISSUE TITLE
New ux - Commentaires

### ISSUE THREAD

**Issue by TrekPiston** [xou816/edt-ecn#1]
## Page principale
* flèche de navigation semaine non statique (la position horizontale évolue en fonction de la date) du coup pour naviguer rapidement entre les semaines il faut faire des ajustement sur le curseur.... (j'ai l'impression que c'est accentué sur mobile)
* Le code couleur est vraiment top je suis fan
* la présentation est aussi franchement réussi j'apprécie beaucoup
* j'ai l'impression que les URL sont "plus propre" (genre avant il y avait des # un peu sauvage non ?)
## Page /ics
* mettre une capture d'écran sur la page /ics de où coller le lien dans google agenda ? 

## Calendrier
alors pour l'ajout du calendrier je suis un peu en mode "ok ça ajoute un truc mais la plus value est pas ouf ouf" mais je pense que avec quelques fonctionnalités en plus ça peut être vraiment cool : 
* est ce que l'ajout des numéros de semaine est possible ? 
* ah oui un petit glitch : la par exemple je suis en semaine du 24 septembre et quand je clique sur le samedi il ne se passe rien (pas de changement de semaine) mais quand je clique sur le dimanche l'edt passe sur la semaine suivante mais le mini calendrier ne bouge pas.... J'ai une [vidéo](https://github.com/xou816/edt-ecn/files/2414433/media1.zip) de côté si jamais le glitch n'est pas reproductible de ton côté (ou si jamais je suis pas clair)
* quand la semaine est surligné en rose, est ce que c'est possible de mettre en valeur le jour d'aujourd'hui ? 

Voila globalement c'était mes remarques à chaud, j'ai pas trop de choses à rajouter à froid :) 

Sinon le passage de Desktop à mobile est vraiment propre c'est impressionnant !

Donc GGWP cette refonte est bien cool !

**Comment by xou816** [comment]
- merci pour les retours déjà :D 
- les flèches sont maintenant côte à côte pour éviter ce soucis (et elles sont cachés sur mobile de toute manière)
- je rajouterais une capture sur la page ics :)
- numéro de semaines : difficile (long) sur le mini calendrier, je l'ai mis dans la headerbar à la place!
- très très bien vu le glitch! c'est corrigé
- bien vu pour le surlignement, je prend en compte!

**Comment by TrekPiston** [comment]
Une autre petite remarque : le curseur horaire est des fois dans les choux : 

Ex ici il est 7h44 (donc avant 8h) et le curseur est tout en bas et "sort de la page", peut être une condition sur sa visibilité ? 

![image](https://user-images.githubusercontent.com/41018128/46059613-44cb5e80-c160-11e8-86aa-ff69654d03fa.png)
